import JsBarcode from 'jsbarcode';
import PropTypes from 'prop-types';
import { useEffect, useRef } from 'react';

/**
 * Renders a scannable barcode (CODE128 by default) as an SVG.
 *
 * The SVG is generated by JsBarcode directly into a ref'd <svg> element,
 * which keeps it crisp at any zoom/print size without relying on canvas.
 */
const Barcode = ({
  value = '',
  format = 'CODE128',
  width = 2,
  height = 60,
  fontSize = 14,
  margin = 4,
  displayValue = true,
  background = '#ffffff',
  lineColor = '#000000',
  className = '',
}) => {
  const ref = useRef(null);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    if (!value) {
      el.innerHTML = '';
      return;
    }
    try {
      JsBarcode(el, String(value), {
        format,
        width,
        height,
        fontSize,
        margin,
        displayValue,
        background,
        lineColor,
      });
    } catch (err) {
      el.innerHTML = '';
      // eslint-disable-next-line no-console
      console.warn('[Barcode] failed to render', value, err?.message);
    }
  }, [value, format, width, height, fontSize, margin, displayValue, background, lineColor]);

  return (
    <svg
      ref={ref}
      className={className}
      style={{ overflow: 'visible', display: 'block', maxWidth: '100%', height: 'auto' }}
    />
  );
};

Barcode.propTypes = {
  value: PropTypes.string,
  format: PropTypes.string,
  width: PropTypes.number,
  height: PropTypes.number,
  fontSize: PropTypes.number,
  margin: PropTypes.number,
  displayValue: PropTypes.bool,
  background: PropTypes.string,
  lineColor: PropTypes.string,
  className: PropTypes.string,
};

export default Barcode;
